//#define DONT_USE_GENERATE_CODE  

//------------------------------------------------------------------------------    
// <auto-generated>                                                                 
//     This code was generated by Tools.CodeGenerator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null. 
//     https://github.com/JiepengTan/LockstepEngine                                          
//     Changes to this file may cause incorrect behavior and will be lost if        
//     the code is regenerated.                                                     
// </auto-generated>                                                                
//------------------------------------------------------------------------------  

using System;                                                                                                 
using System.Collections.Generic;                                                                             
using Lockstep.Serialization;                                                                                 
using Lockstep.Math;                                                                                 
using NetMsg.Common;                                                                                 
                                                                                         
                                                                                                              
#if !DONT_USE_GENERATE_CODE                                                                                   

namespace Lockstep.Game{                                                                                               
    public partial class GameConstStateService  {                                                                
		public LVector2 CampPos {get; set; }
		public Boolean IsPlaying {get; set; }
		public LVector2Int MapMax {get; set; }
		public LVector2Int MapMin {get; set; }
		public Int32 MaxEnemyCountInScene {get; set; }
		public Int32 MaxPlayerCount {get; set; }
		public Int32 PlayerInitLifeCount {get; set; }
		public Int32 TotalEnemyCountToBorn {get; set; }
		public List<Lockstep.Math.LVector2> EnemyBornPoints {get; set; }
		public List<Lockstep.Math.LVector2> PlayerBornPoss {get; set; }                                                                                                   
   }                                                                                                                 
}                                                                                                                 
namespace Lockstep.Game{                                                                                               
    public partial interface IGameConstStateService  {                                                                
		LVector2 CampPos {get; set; }
		Boolean IsPlaying {get; set; }
		LVector2Int MapMax {get; set; }
		LVector2Int MapMin {get; set; }
		Int32 MaxEnemyCountInScene {get; set; }
		Int32 MaxPlayerCount {get; set; }
		Int32 PlayerInitLifeCount {get; set; }
		Int32 TotalEnemyCountToBorn {get; set; }
		List<Lockstep.Math.LVector2> EnemyBornPoints {get; set; }
		List<Lockstep.Math.LVector2> PlayerBornPoss {get; set; }                                                                                                   
   }                                                                                                                 
}                                                                                                                
                                                                                           
#endif                                                                                                        
  