//#define DONT_USE_GENERATE_CODE  

//------------------------------------------------------------------------------    
// <auto-generated>                                                                 
//     This code was generated by Tools.CodeGenerator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null. 
//     https://github.com/JiepengTan/LockstepEngine                                          
//     Changes to this file may cause incorrect behavior and will be lost if        
//     the code is regenerated.                                                     
// </auto-generated>                                                                
//------------------------------------------------------------------------------  

using System;                                                                                                 
using System.Collections.Generic;                                                                             
using Lockstep.Serialization;                                                                                 
using Lockstep.Math;                                                                                 
using NetMsg.Common;                                                                                 
                                                                                         
                                                                                                              
#if !DONT_USE_GENERATE_CODE                                                                                   

namespace Lockstep.Game{                                                                                               
   public partial interface IGameStateService  {                                                                
		LFloat BornInterval {get; set; }
		LFloat BornTimer {get; set; }
		Int32 CurEnemyCountInScene {get; set; }
		UInt32 LocalEntityId {get; set; }
		Int32 RemainCountToBorn {get; set; }                                                                                                   
   }                                                                                                                 
}                                                                                                                 
namespace Lockstep.Game{                                                                                               
    public partial class GameStateService  {                                                                                
        private _State _curState = new _State();                                                                       
        public class CopyStateCmd : BaseCommand {                                                                      
            private _State state;                                                                                      
            public override void Do(object param){                                                                     
                state = ((GameStateService) param)._curState;                                                              
            }                                                                                                            
                                                                                                                         
            public override void Undo(object param){                                                                     
                ((GameStateService) param)._curState = state;                                                            
            }                                                                                                            
        }                                                                                                              
        public override void Backup(int tick){                                                                         
            cmdBuffer.Execute(tick, new CopyStateCmd());                                                                 
        }                                                                                                              
        protected override FuncUndoCommands GetRollbackFunc(){                                                         
            return (minTickNode, maxTickNode, param) => { minTickNode.cmd.Undo(param); };                                
        }                                                                                                              
        public struct _State {                                                                                        
			public LFloat BornInterval;
			public LFloat BornTimer;
			public Int32 CurEnemyCountInScene;
			public UInt32 LocalEntityId;
			public Int32 RemainCountToBorn;                                                                                                
        }                                                                                                              
		public LFloat BornInterval {get => _curState.BornInterval;set => _curState.BornInterval = value;}
		public LFloat BornTimer {get => _curState.BornTimer;set => _curState.BornTimer = value;}
		public Int32 CurEnemyCountInScene {get => _curState.CurEnemyCountInScene;set => _curState.CurEnemyCountInScene = value;}
		public UInt32 LocalEntityId {get => _curState.LocalEntityId;set => _curState.LocalEntityId = value;}
		public Int32 RemainCountToBorn {get => _curState.RemainCountToBorn;set => _curState.RemainCountToBorn = value;}                                                                                                
   }                                                                                                              
}                                                                                                             
                                                                                           
#endif                                                                                                        
  