
//------------------------------------------------------------------------------    
// <auto-generated>                                                                 
//     This code was generated by Tools.ExcelParser, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null. 
//     https://github.com/JiepengTan/LockstepEngine                                          
//     Changes to this file may cause incorrect behavior and will be lost if        
//     the code is regenerated.                                                     
// </auto-generated>                                                                
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using Lockstep.Serialization;
using Lockstep.Math;

namespace Lockstep.Game{
    public partial class Table_ConfigCamp : TableData<Table_ConfigCamp>
    {
        const string tableName = "ConfigCamp";
        public override string Name() { return tableName; }               
        
        /// id
        public UInt16 asset;        
        /// 
        public String unit_name;        
        /// 
        public Int32 unit_health;        
        /// 
        public Int32 unit_damage;

        protected override void DoParseData(Deserializer reader){ 
            asset = reader.ReadUInt16(); 
            unit_name = reader.ReadString(); 
            unit_health = reader.ReadInt32(); 
            unit_damage = reader.ReadInt32();
        }
    }
}