
//------------------------------------------------------------------------------    
// <auto-generated>                                                                 
//     This code was generated by Tools.ExcelParser, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null. 
//     https://github.com/JiepengTan/LockstepEngine                                          
//     Changes to this file may cause incorrect behavior and will be lost if        
//     the code is regenerated.                                                     
// </auto-generated>                                                                
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using Lockstep.Serialization;
using Lockstep.Math;

namespace Lockstep.Game{
    public partial class Table_Assets : TableData<Table_Assets>
    {
        const string tableName = "Assets";
        public override string Name() { return tableName; }               
        
        /// id
        public Int32 id;        
        /// 目录
        public String dir;        
        /// 名字
        public String name;        
        /// 后缀
        public String suffix;

        protected override void DoParseData(Deserializer reader){ 
            id = reader.ReadInt32(); 
            dir = reader.ReadString(); 
            name = reader.ReadString(); 
            suffix = reader.ReadString();
        }
    }
}