//#define DONT_USE_GENERATE_CODE  

//------------------------------------------------------------------------------    
// <auto-generated>                                                                 
//     This code was generated by Engine.LockstepEngine, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null. 
//     https://github.com/JiepengTan/LockstepEngine                                          
//     Changes to this file may cause incorrect behavior and will be lost if        
//     the code is regenerated.                                                     
// </auto-generated>                                                                
//------------------------------------------------------------------------------  

using System;                                                                                                 
using System.Collections.Generic;                                                                             
using Lockstep.Serialization;                                                                                 
using Lockstep.Math;                                                                                 
using NetMsg.Common;                                                                                 
                                                                                         
                                                                                                              
#if !DONT_USE_GENERATE_CODE                                                                                   

namespace Lockstep.Game{                                                                                               
    public partial class GameStateService  {                                                                                
       private _State _curState = new _State();                                                                       
       public class CopyStateCmd : BaseCommand {                                                                      
           private _State state;                                                                                      
           public override void Do(object param){                                                                     
               state = ((GameStateService) param)._curState;                                                              
           }                                                                                                            
                                                                                                                        
           public override void Undo(object param){                                                                     
               ((GameStateService) param)._curState = state;                                                            
           }                                                                                                            
       }                                                                                                              
       public override void Backup(int tick){                                                                         
           cmdBuffer.Execute(tick, new CopyStateCmd());                                                                 
       }                                                                                                              
       protected override FuncUndoCommands GetRollbackFunc(){                                                         
           return (minTickNode, maxTickNode, param) => { minTickNode.cmd.Undo(param); };                                
       }                                                                                                              
       public struct _State {                                                                                        
			public LFloat bornInterval;
			public LFloat bornTimer;
			public Int32 curEnemyCountInScene;
			public UInt32 localEntityId;
			public Int32 remainCountToBorn;                                                                                                
       }                                                                                                              
			public LFloat bornInterval {get => _curState.bornInterval;set => _curState.bornInterval = value;}
			public LFloat bornTimer {get => _curState.bornTimer;set => _curState.bornTimer = value;}
			public Int32 curEnemyCountInScene {get => _curState.curEnemyCountInScene;set => _curState.curEnemyCountInScene = value;}
			public UInt32 localEntityId {get => _curState.localEntityId;set => _curState.localEntityId = value;}
			public Int32 remainCountToBorn {get => _curState.remainCountToBorn;set => _curState.remainCountToBorn = value;}                                                                                                
   }                                                                                                              
}                                                                                                             
                                                                                           
#endif                                                                                                        
  