//#define DONT_USE_GENERATE_CODE  

//------------------------------------------------------------------------------    
// <auto-generated>                                                                 
//     This code was generated by Engine.LockstepEngine, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null. 
//     https://github.com/JiepengTan/LockstepEngine                                          
//     Changes to this file may cause incorrect behavior and will be lost if        
//     the code is regenerated.                                                     
// </auto-generated>                                                                
//------------------------------------------------------------------------------  

using System;                                                                                                 
using System.Collections.Generic;                                                                             
using Lockstep.Serialization;                                                                                 
using Lockstep.Math;                                                                                 
using NetMsg.Common;                                                                                 
                                                                                         
                                                                                                              
#if !DONT_USE_GENERATE_CODE                                                                                   

namespace Lockstep.Game{                                                                                               
    public partial class GameConstStateService  {                                                                
			public Boolean IsPlaying {get; set; }
			public Int32 MaxEnemyCountInScene {get; set; }
			public Int32 MaxPlayerCount {get; set; }
			public Int32 TotalEnemyCountToBorn {get; set; }
			public LVector2 campPos {get; set; }
			public LVector2Int mapMax {get; set; }
			public LVector2Int mapMin {get; set; }
			public Int32 playerInitLifeCount {get; set; }
			public Msg_G2C_GameStartInfo GameStartInfo {get; set; }
			public List<Lockstep.Math.LVector2> enemyBornPoints {get; set; }
			public List<Lockstep.Math.LVector2> playerBornPoss {get; set; }                                                                                                   
   }                                                                                                                 
}                                                                                                                
                                                                                           
#endif                                                                                                        
  