//#define DONT_USE_GENERATE_CODE  

//------------------------------------------------------------------------------    
// <auto-generated>                                                                 
//     This code was generated by Engine.LockstepEngine, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null. 
//     https://github.com/JiepengTan/LockstepEngine                                          
//     Changes to this file may cause incorrect behavior and will be lost if        
//     the code is regenerated.                                                     
// </auto-generated>                                                                
//------------------------------------------------------------------------------  

using System;                                                                                                 
using System.Collections.Generic;                                                                             
using Lockstep.Serialization;                                                                                 
using Lockstep.Math;                                                                                 
using NetMsg.Common;                                                                                 
                                                                                         
                                                                                                              
#if !DONT_USE_GENERATE_CODE                                                                                   

namespace Lockstep.Game{                                                                                               
    public partial class GameConfigService  {                                                                                
			public Single BornEnemyInterval {get => _config.BornEnemyInterval;set => _config.BornEnemyInterval = value;}
			public Int16 BornPrefabAssetId {get => _config.BornPrefabAssetId;set => _config.BornPrefabAssetId = value;}
			public Int16 DiedPrefabAssetId {get => _config.DiedPrefabAssetId;set => _config.DiedPrefabAssetId = value;}
			public String DumpStrPath {get => _config.DumpStrPath;set => _config.DumpStrPath = value;}
			public Int32 InitEnemyCount {get => _config.InitEnemyCount;set => _config.InitEnemyCount = value;}
			public Int32 MaxEnemyCount {get => _config.MaxEnemyCount;set => _config.MaxEnemyCount = value;}
			public Int32 MaxPlayerCount {get => _config.MaxPlayerCount;set => _config.MaxPlayerCount = value;}
			public String RecorderFilePath {get => _config.RecorderFilePath;set => _config.RecorderFilePath = value;}
			public String RelPath {get => _config.RelPath;set => _config.RelPath = value;}
			public LFloat TankBornDelay {get => _config.TankBornDelay;set => _config.TankBornDelay = value;}
			public LVector2 TankBornOffset {get => _config.TankBornOffset;set => _config.TankBornOffset = value;}
			public Msg_G2C_GameStartInfo ClientModeInfo {get => _config.ClientModeInfo;set => _config.ClientModeInfo = value;}
			public CollisionConfig CollisionConfig {get => _config.CollisionConfig;set => _config.CollisionConfig = value;}                                                                                                       
    }                                                                                                           
                                                                                               
    public partial class GameConfig  {                                                                                
			public Single BornEnemyInterval;
			public Int16 BornPrefabAssetId;
			public Int16 DiedPrefabAssetId;
			public String DumpStrPath;
			public Int32 InitEnemyCount;
			public Int32 MaxEnemyCount;
			public Int32 MaxPlayerCount;
			public String RecorderFilePath;
			public String RelPath;
			public LFloat TankBornDelay;
			public LVector2 TankBornOffset;
			public Msg_G2C_GameStartInfo ClientModeInfo;
			public CollisionConfig CollisionConfig;                                                                                                       
    }                                                                                                           
}                                                                                                                   
                                                                                           
#endif                                                                                                        
  