
//------------------------------------------------------------------------------    
// <auto-generated>                                                                 
//     This code was generated by Tools.ECSGenerator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null. 
//     https://github.com/JiepengTan/LockstepEngine                                          
//     Changes to this file may cause incorrect behavior and will be lost if        
//     the code is regenerated.                                                     
// </auto-generated>                                                                
//------------------------------------------------------------------------------  

using Entitas.CodeGeneration.Attributes;                                            
using Lockstep.Math;                                                                
using Entitas;                                                                      
using System;                                                                       
using Lockstep.Serialization; 

namespace Lockstep.ECS.Actor{
    [Actor]
    public partial class GameEntityIdComponent :Entitas.IComponent {
        public uint value;
    }

    [Event(EventTarget.Self)]
    [Actor]
    public partial class LifeComponent :Entitas.IComponent {
        public int value;
    }

    [Actor]
    public partial class ActorIdComponent :Entitas.IComponent {
        [PrimaryEntityIndex]public byte value;
    }

    [Actor]
    public partial class BackupComponent :Entitas.IComponent {
        public byte actorId;
        public int tick;
    }

    [Event(EventTarget.Self)]
    [Actor]
    public partial class ScoreComponent :Entitas.IComponent {
        public int value;
    }

}
