
//------------------------------------------------------------------------------    
// <auto-generated>                                                                 
//     This code was generated by Tools.ECSGenerator, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null. 
//     https://github.com/JiepengTan/LockstepEngine                                          
//     Changes to this file may cause incorrect behavior and will be lost if        
//     the code is regenerated.                                                     
// </auto-generated>                                                                
//------------------------------------------------------------------------------  

using Entitas.CodeGeneration.Attributes;                                            
using Lockstep.Math;                                                                
using Entitas;                                                                      
using System;                                                                       
using Lockstep.Serialization; 

namespace Lockstep.ECS.Game{
    [Game]
    public partial class BornPointComponent :Entitas.IComponent {
        public LVector2 pos;
    }

    [Game]
    public partial class MoveComponent :Entitas.IComponent {
        public LFloat moveSpd;
        public LFloat maxMoveSpd;
        public bool isChangedDir;
    }

    [Game]
    public partial class AIComponent :Entitas.IComponent {
        public LFloat timer;
        public LFloat updateInterval;
        public LFloat fireRate;
    }

    [Game]
    public partial class SkillComponent :Entitas.IComponent {
        public LFloat cd;
        public LFloat cdTimer;
        public int bulletId;
        public bool isNeedFire;
    }

    [Game]
    public partial class BulletComponent :Entitas.IComponent {
        public bool canDestoryIron;
        public bool canDestoryGrass;
        public uint ownerLocalId;
    }

    [Game]
    public partial class OwnerComponent :Entitas.IComponent {
        public uint localId;
    }

    [Game]
    public partial class DropRateComponent :Entitas.IComponent {
        public LFloat value;
    }

    [Game]
    public partial class UnitComponent :Entitas.IComponent {
        public string name;
        public Lockstep.Game.ECampType camp;
        public int health;
        public int damage;
        public uint killerLocalId;
    }

    [Game]
    public partial class BackupComponent :Entitas.IComponent {
        public uint entityId;
        public int tick;
    }

    [Game]
    public partial class ActorIdComponent :Entitas.IComponent {
        public byte value;
    }

    [Game]
    public partial class DestroyedComponent :Entitas.IComponent {
    }

    [Game]
    public partial class DelayCallComponent :Entitas.IComponent {
        public LFloat delayTimer;
        public int callBackId;
    }

    [Game]
    public partial class ItemTypeComponent :Entitas.IComponent {
        public Lockstep.Game.EItemType type;
        public byte killerActorId;
    }

    [Game]
    public partial class EntityIdComponent :Entitas.IComponent {
        [PrimaryEntityIndex]public uint value;
    }

    [Game]
    public partial class MoveRequestComponent :Entitas.IComponent {
        public Lockstep.Game.EDir value;
    }

    [Game]
    public partial class FireRequestComponent :Entitas.IComponent {
    }

    [Game]
    public partial class TagCampComponent :Entitas.IComponent {
    }

    [Game]
    public partial class TagEnemyComponent :Entitas.IComponent {
    }

    [Game]
    public partial class TagTankComponent :Entitas.IComponent {
    }

    [Game]
    public partial class TagBulletComponent :Entitas.IComponent {
    }

    [Game]
    public partial class AssetComponent :Entitas.IComponent {
        public ushort assetId;
    }

    [Game]
    public partial class ConfigIdComponent :Entitas.IComponent {
        public int id;
    }

    [Game]
    public partial class PosComponent :Entitas.IComponent {
        public LVector2 value;
    }

    [Game]
    public partial class DirComponent :Entitas.IComponent {
        public Lockstep.Game.EDir value;
    }

    [Game]
    public partial class ColliderComponent :Entitas.IComponent {
        public LVector2 size;
        public LFloat radius;
    }

}
