#!/bin/bash
clear
dir="$(cd $(dirname ${BASH_SOURCE[0]}) && pwd)"
cd $dir/../
pwd
rm -rf ./Src/Client.Unity/Assets/Scripts/Engine.LockstepEngine
cp -rf ./Src/Engine.LockstepEngine/Src/LockstepEngine/ ./Src/Client.Unity/Assets/Scripts/Engine.LockstepEngine/ 

