
//------------------------------------------------------------------------------    
// <auto-generated>                                                                 
//     This code was generated by Tools.ECS2Excel, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null. 
//     https://github.com/JiepengTan/LockstepEngine                                          
//     Changes to this file may cause incorrect behavior and will be lost if        
//     the code is regenerated.                                                     
// </auto-generated>                                                                
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using Lockstep.Serialization;
using Lockstep.Math;
using Entitas;

namespace Lockstep.Game{
    public partial class EntityUtil{
        private static GameEntity CreateEntityCamp(GameContext context){
            var entity = context.CreateEntity();
            AddComponent<Lockstep.ECS.Game.UnitComponent>(entity,GameComponentsLookup.Unit);
            AddComponent<Lockstep.ECS.Game.TagCampComponent>(entity,GameComponentsLookup.TagCamp);
            AddComponent<Lockstep.ECS.Game.AssetComponent>(entity,GameComponentsLookup.Asset);
            AddComponent<Lockstep.ECS.Game.DirComponent>(entity,GameComponentsLookup.Dir);
            AddComponent<Lockstep.ECS.Game.PosComponent>(entity,GameComponentsLookup.Pos);
            AddComponent<Lockstep.ECS.Game.ColliderComponent>(entity,GameComponentsLookup.Collider);
            return entity;
        }
        public static GameEntity CreateEntityCamp(GameContext context, ushort prefabId){
            var entity = CreateEntityCamp(context);
            var tblData = Table_ConfigCamp.GetData(prefabId);
            tblData.AssignToEntity(entity);
            return entity; 
        }
    }
    public partial class Table_ConfigCamp :IAssignToEntity
    {
        public void AssignToEntity(object entityObj){ 
            var entity = (GameEntity)entityObj;
            entity.asset.assetId = asset;
            entity.unit.name = unit_name;
            entity.unit.health = unit_health;
            entity.unit.damage = unit_damage;
        }
    }
}